### ISSUE TITLE
Support for UI-Router

### ISSUE THREAD

**Issue by tarkanlar** [AvraamMavridis/angular-metatags#1]

**Comment by AvraamMavridis** [comment]
@tarkanlar Can you write a bit description about?

**Comment by tarkanlar** [comment]
Thanks @AvraamMavridis , i thought it would be perfect if integrated with ui-router. We already define roots there so if there will be an opportunity to add this to Ui-router would be great. could be a silly idea too :))

**Comment by ghost** [comment]
+1 Would love this kind of functionality for UI router

**Comment by AvraamMavridis** [comment]
@KoalaOnAStick  I will look into that when I have some time. Thx for the suggestion :+1:

**Comment by klaoha06** [comment]
+1

**Comment by amatosc** [comment]
+1

**Comment by piotrd** [comment]
Any update on this subject?

**Comment by pbassut** [comment]
+1
