### ISSUE TITLE
hi, this does not support facebook?

### ISSUE THREAD

**Issue by fkkcloud** [AvraamMavridis/angular-metatags#6]
I still get {{metatags.fb_title}} when I share.. to facebook feed.

http://www.enteractive.space/finalfantasy

**Comment by AvraamMavridis** [comment]
@fkkcloud  are you using prerender.io or brombone to serve prerendered pages? Otherwise it will not work. It is a general issue of js frameworks, not angular specific. https://builtvisible.com/javascript-framework-seo/

**Comment by AvraamMavridis** [comment]
Closing this issue. I think my previous reply answers your question.
